version: 2

defaults: &defaults
  docker:
    - image: canonicalwebteam/dev:v1.6.3

jobs:
  linkchecker:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install Linkchecker
          command: apt-get install -y linkchecker
      - run:
          name: Yarn install
          command: yarn install
      - run:
          name: Yarn build
          command: yarn build
      - run:
          name: Install dependencies
          command: pip3 install -r requirements.txt
      - run:
          name: Start development server
          command: ./entrypoint 0.0.0.0:80
          background: true
      - run:
          name: Wait for development server
          command: sleep 5
      - run:
          name: Run Linkchecker
          command: linkchecker --threads 2 --ignore-url /usn --ignore-url /search --ignore-url ".*(?:png|jpg|jpeg|gif|bmp|svg|js)$" --ignore-url /q_auto --ignore-url /fl_sanitize --ignore-url /w_* --ignore-url /blog --no-warnings http://127.0.0.1
  lint-python:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Lint python code
          command: yarn lint-python
  lint-scss:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn
      - run:
          name: Lint sass
          command: yarn lint-scss
  python-tests:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install requirements
          command: pip3 install -r requirements.txt
      - run:
          name: Install dependencies
          command: pip3 install coverage
      - run:
          name: Run tests with coverage
          command: |
            coverage run  --source=. -m unittest discover tests
            bash <(curl -s https://codecov.io/bash) -cF python
workflows:
  version: 2
  build:
    jobs:
      - linkchecker
      - lint-scss
      - lint-python
